norahito/dive23

config/application.rb

#1 
config/application.rbに設定を行いました。

【Fixed】rails g の際に無駄にhelperとassetsが生成されないようにしました。

---

Gemfile
Gemfile.lock
config/environments/development.rb

#2 
Gemfileに追記。
group :development do
　gem 'pry-rails'
　gem 'better_errors'
　gem 'binding_of_caller'
end
better_errorsの初期設定のため、
config/environments/development.rbに、以下を記述。
BetterErrors::Middleware.allow_ip! "0.0.0.0/0"

【Fixed】デバッグツールを導入する

---

app/models/answer.rb
app/models/user.rb
db/migrate/20160821073010_create_answers.rb
db/schema.rb
spec/models/answer_spec.rb
spec/models/user_spec.rb

【Fixed】ユーザー(users)と回答(answers)間の関連を設定

---

app/models/answer.rb
app/models/vote.rb
db/migrate/20160821074134_create_votes.rb
db/schema.rb
spec/models/answer_spec.rb
spec/models/vote_spec.rb

【Fixed】回答(answers)と投票(votes)間の関連を設定

---

app/models/question.rb
app/models/tag_relation.rb
db/migrate/20160821060841_create_tag_relations.rb
db/schema.rb
spec/models/question_spec.rb
spec/models/tag_relation_spec.rb

【Fixed】質問(qusetions)とタグ関連(tag_relations)間のrelationを設定する

---

app/controllers/questions_controller.rb
app/models/question.rb

質問(questions)の削除を物理削除から論理削除に変更する

---

spec/models/question_spec.rb

#52 
記述ミスを修正しました。
修正前）
#ユーザIDが記入されていなければNG
it "is invalid without content"
修正後）
#ユーザIDが記入されていなければNG
it "is invalid without user_id"

【Fixed】質問の単体テストクラス(question_spec.rb)の記述ミスの修正

---

app/controllers/application_controller.rb
app/controllers/questions_controller.rb
app/views/questions/index.html.erb
db/schema.rb

#61
- 質問の閲覧は誰でも可
- QuestionsControllerのindexアクションとshowアクションはauthenticate_user!によるフィルタをスキップ
- 質問の投稿は、ログインユーザのみ可
- ApplicationControllerにフィルタとしてauthenticate_user!を追加
- 自分の質問のみ、編集・削除可
- 自分の質問のみ編集・削除のリンクを表示するようビューを修正
- 自分の質問以外の編集・削除リクエストがサーバに送られた際、処理をせず、質問一覧画面へリダイレクトする処理を追加

【Fixed】質問(question)コントローラに操作権限の設定を行う

---

app/controllers/questions_controller.rb
app/views/questions/_form.html.erb
app/views/questions/edit.html.erb
app/views/questions/new.html.erb

issues#85
・質問画面から画面タイトルと不要なボタンを削除。
・user_idを内部でセット。
・質問詳細画面の調整は別issue。(issue#30 回答(answers)用のViewを作成 )
・画面レイアウト、タグの関連付け機能、CSS等の詳細なデザインは別イシューで。

【Fixed】質問画面の調整（user_idのセットと画面表示項目の調整） 

---

app/controllers/questions_controller.rb
app/views/questions/index.html.erb

issues#88
・質問一覧画面(TOP画面)から不要な項目とボタンを削除しグリッドシステムを導入。
・タブによるソート順の切り替えを実装。（更新日時降順、お気に入り降順）
・このissueではおおまかな画面の調整を行う。CSS等の詳細なデザインは別イシューで。

【Fixed】質問一覧画面(TOP画面)の調整（画面表示項目の調整等） 

---

app/models/answer.rb
spec/factories/answers.rb
spec/models/answer_spec.rb

#34 
・モデルにバリデーションの設定を行う。 →content, user_id, question_id 空NG
・バリデーションが正しく機能しているか単体テストで確認する。

【Fixed】Answerモデルのバリデーション設定とそのテスト

---

app/uploaders/avatar_uploader.rb

issues#123
幾つかの画像を試した結果resize_to_fillが良かったので
resize_to_fitからresize_to_fillへ変換方式を変える。

avatorのリサイズ方式をresize_to_fitをresize_to_fillに変える 

---

spec/controllers/favorites_controller_spec.rb

issues#121
以下の内容を、rails g controllerの際に自動生成されたもののため、削除。
describe "GET #create" do
it "returns http success" do
get :create
expect(response).to have_http_status(:success)
end
end
describe "GET #destroy" do
it "returns http success" do
get :destroy
expect(response).to have_http_status(:success)
end
end

【Fixed】favorites_controller_spec.rb中身を削除

---

app/controllers/favorites_controller.rb
spec/controllers/favorites_controller_spec.rb

issues#115
favoriteの登録・削除時に関連するquestionsのfavorite_countsを増減させる。
・お気に入りのcreate時に1加算。
・お気に入りのdestroy時に1減算。
・原子性を保証するため一つのtransaction内で更新する。

【Fixed】お気に入りの登録・削除時にquesitonsのfavorite_countsを増減させる。

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/common.scss
app/controllers/questions_controller.rb
app/models/question.rb
app/models/tag.rb
app/views/questions/_form.html.erb
app/views/questions/index.html.erb
vendor/assets/javascripts/tag-it.js
vendor/assets/stylesheets/jquery.tagit.css
vendor/assets/stylesheets/tagit.ui-zendesk.css

Issues#131 
新規質問作成画面にTagの紐づけ機能を実装する。
質問を登録した際に関連する3テーブルの同時更新を行っている。(tags, tag_relations, questions)
画面回りはgemの"jQUery Tag-it"を利用した。
参考URL：
http://qiita.com/tyamagu2/items/75eeaa8ef208385aa341
https://github.com/aehlke/tag-it/blob/master/README.markdown
裏側の仕組みはあえてgem"acts-as-taggable-on"を使用せずに下記のURLの「ゼロからタグ機能を実装する」の項を参考に実装した。
参考URL：
http://railscasts.com/episodes/382-tagging?language=ja&view=asciicast
画面の詳細なデザインとJavaScriptの外だしは別イシューで。

【Fixed】Tagの紐づけ機能を実装する

---

app/assets/stylesheets/partials/_question.scss
app/views/questions/show.html.erb

#140 
・ユーザー名の表示（＆ユーザー詳細ページのリンク）
・質問作成時間の表示修正（time_format使用）
・ユーザ画面の表示
・ユーザー貢献度の表示

【Fixed】質問詳細ページの質問作成ユーザーの表示（内容＆デザイン）修正

---

app/assets/stylesheets/partials/_users.scss
app/controllers/users_controller.rb
app/views/users/show.html.erb
config/initializers/time_formats.rb

ユーザ詳細ページに、ユーザが投稿した質問と回答の一覧表示を作成。
新着順と票数順に並び替えできるようにも設定。
本家では、質問と回答が一緒になった状態で、新着順と票数順に並び替えできるようになっていたが、質問と回答が別テーブルなのでやろうとすると、めっちゃ大変かなと思い、今回は断念。
また、回答の一覧で、リンクをクリックすると、その回答の質問詳細ページにリンクします。本来なら、質問詳細ページの中の、その回答へピンポイントでリンクすべきですが、もしやるなら別issuでお願いしたいと思います。

【Fixed】ユーザー詳細ページへ投稿質問・回答の一覧を表示

---

app/views/users/show.html.erb

#152 
ユーザー詳細ページを作成したときの、ミスを修正です。
プロフィール表示部分で、ユーザが何もプロフィールを入力していない場合、
自分のユーザページの場合とそうじゃない場合で、表示を変更するように設定しました。

【Fixed】ユーザー詳細画面にて、編集画面へのリンク部分を修正

---

app/assets/stylesheets/partials/_common.scss
app/assets/stylesheets/partials/_favorite.scss
app/assets/stylesheets/partials/_question.scss
app/views/questions/_favorite_form.html.erb
app/views/questions/index.html.erb

#143
一覧画面(TOPページ)を本家のデザインに近づけました。
本家だと、ロゴマークをクリックして表示される質問一覧（サブタイトルが上位の質問)と、
ヘッドメニューの"質問"をクリックして表示される質問一覧（サブタイトルが"すべての質問）で、
デザインが異なりますが、今回は後者に合わせました。

【Fixed】一覧画面(TOPページ)にスタイルを適用する

---

app/controllers/questions_controller.rb
app/models/question.rb
app/views/questions/_index.html.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
app/views/questions/tagged.html.erb
app/views/tags/index.html.erb
config/routes.rb

issues#137
タグをクリックした際にそのタグに紐づく質問を一覧表示する機能と画面を作成する。
リンク元の画面は下記の通り。
+ 質問詳細ページ
+ 質問一覧ページ
+ タグ一覧ページ

【Fixed】Tagによる質問の検索機能の実装

---

app/controllers/application_controller.rb
app/controllers/users/registrations_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
config/locales/devise.ja.yml
config/routes.rb

Issues#111
Userアカウントの削除を論理削除に変更
stack overflowの仕様(http://ja.stackoverflow.com/help/deleting-account)を参考に下記の様な仕様にした。
+ 削除されたアカウントは匿名ユーザーとなり、質問と回答は残す。
+ 匿名ユーザーの投票は論理削除し質問、回答の投票数をカウントを減らす。(Userのスコアはそのまま)
+ 削除されたアカウントではログイン出来ない。
+ 削除されたユーザーの写真、名前等のプロフィールはクリアする。
+ 削除されたアカウントはユーザー一覧に表示されない。
+ 削除されたアカウントと同じメールアドレスで再登録が出来る。

【Fixed】USERモデルの削除（アカウント削除）を論理削除に変更

---

app/controllers/answers_controller.rb
app/controllers/questions_controller.rb
app/models/favorite.rb
app/models/tag_relation.rb
app/models/vote.rb

Issues#165
質問と回答を論理削除する際に関連テーブルも論理削除を行う。
質問削除
+ favorites
+ tag_relations
+ votes
+ answers
+ answersに対するvotes
回答削除
+ votes

【Fixed】質問と回答を論理削除する際の関連テーブルの論理削除

---

app/views/users/show.html.erb
config/initializers/time_formats.rb

issues#166
マイページのプロフィールにある質問、回答一覧の新着順タブを押下した際に
時刻が表示されていないので新着順になっているかが分からない。
フォーマットを変更し日時を表示する様にする。

【FIxed】マイページの日時フォーマット修正
