.gitignore, Gemfile, Gemfile.lock
#3 
・gem 'dotenv-rails"追加
・.envファイル生成
・.gitignoreに以下を追記
.env
/public/uploads/* 
.DS_Store
.localized
（すいません、自分macでないため、自分でもググって追記の仕方調べましたが、念のため、要確認お願いいたします）
=> 【Fixed】不要なコミットを避けるためignoreの設定を行う。

Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, config/database.yml, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20160815090254_devise_create_users.rb, db/schema.rb, test/fixtures/users.yml, test/models/user_test.rb
#5 
下記を実行しテスト環境での画面表示まで確認。
・初期設定の実行( rails generate devise:install )
・Userモデルの生成
・config/database.ymlに 「template: template0」　を追加する。
・Userテーブルの作成
・DBの作成(migrate)
・Devise用のVIewの生成
=> 【Fixed】ログイン機能に必要なGem( devise )の導入と初期設定

config/application.rb, config/locales/devise.ja.yml, config/locales/ja.yml
#6 
・config/application.rbを修正
・config/locales/直下に以下を作成
　-devise.ja.yml
-ja.yml
=> 【Fixed】日本語化(日本語辞書ファイルを導入)

Gemfile, app/models/question.rb, app/models/user.rb, db/migrate/20160819081036_create_questions.rb, db/schema.rb, spec/factories/questions.rb, spec/models/question_spec.rb
#7 
・Questionモデルを生成する。
→$rails g model Question user:references title:string content:text photo:string favorite_counts:integer posi_counts:integer nega_counts:integer deleted_flg:boolean
・ モデルにバリデーションの設定を行う。
→マイグレーションファイルで、titleとcontentカラムに、null:falseを追加
→同じくマイグレファイルで、counts系のカラムに、default: 0を追加
→同じマイグレファイルで、deleted_flgに、default: falseを追加
→Questionモデルに、バリデーション設定
・UserモデルとQuestionモデルにアソシエーション設定
・マイグレートを実行しテーブルを生成
・バリデーションが正しく機能しているか単体テストで確認
→spec/models/question_spec,rb生成でテストを記述→問題なしだが、最初にbin/rspecを行ったときに、以下のようにエラーがおきたため。Gemfileを修正しました。
```
Web Console is activated in the test environment, which is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:
gem 'web-console', group: :development
If you still want to run it the test …
```
=> 【Fixed】質問モデル(Question)生成と、テーブルの作成

app/models/tag.rb, db/migrate/20160821042943_create_tags.rb, db/schema.rb, spec/factories/tags.rb, spec/models/tag_spec.rb
=> 【Fixed】タグモデル(Tag)の生成とテーブルの作成

app/models/tag_relation.rb, db/migrate/20160821060841_create_tag_relations.rb, db/schema.rb, spec/factories/tag_relations.rb, spec/models/tag_relation_spec.rb
=> 【Fixed】タグ関連モデル(TagRelation)の生成とテーブルの作成

app/models/favorite.rb, db/migrate/20160821071254_create_favorites.rb, db/schema.rb, spec/factories/favorites.rb, spec/models/favorite_spec.rb
issue#21
user_idとquestion_idに関してはとりあえずテーブル作成の為に項目を作成した、
次回リレーション作成時に外部キーに変更する(t.references :user, index: true, foreign_key: true等)。
=> 【Fixed】お気に入りモデル(Favorite)の生成とテーブルの作成

app/models/answer.rb, db/migrate/20160821073010_create_answers.rb, db/schema.rb, spec/factories/answers.rb, spec/models/answer_spec.rb
=> 【Fixed】回答モデル(Answer)の生成とテーブルの作成

app/models/vote.rb, db/migrate/20160821074134_create_votes.rb, db/schema.rb, spec/factories/votes.rb, spec/models/vote_spec.rb
=> 【Fixed】投票モデル(Vote)の生成とテーブルの作成　

db/migrate/20160815090254_devise_create_users.rb, db/schema.rb
=> 【Fixed】usersテーブルにscoreとdeleted_flgのカラムを追加

Gemfile, Gemfile.lock, app/models/favorite.rb, app/models/question.rb, db/migrate/20160821071254_create_favorites.rb, db/schema.rb, spec/models/favorite_spec.rb, spec/models/question_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
issue#40 
質問とお気に入りの間に１：ｎの関連を定義し外部キーとそのインデックスの設定を行った。
=> 質問(Question)とお気に入り(Favorite)間の関連を設定

app/models/favorite.rb, app/models/user.rb, db/migrate/20160821071254_create_favorites.rb, db/schema.rb, spec/models/favorite_spec.rb, spec/models/user_spec.rb
issues#41
ユーザー(User)とお気に入り(Favorite)間に１対ｎの関連を設定。
Rspecによるテストによって関連が正しく設定された事を確認した。
=> ユーザー(User)とお気に入り(Favorite)間の関連を設定

app/models/answer.rb, app/models/question.rb, db/migrate/20160821073010_create_answers.rb, db/schema.rb, spec/models/answer_spec.rb, spec/models/question_spec.rb
=> 【Fixed】質問(Question)と回答(Answer)間の関連を設定

app/models/question.rb, app/models/vote.rb, db/migrate/20160821074134_create_votes.rb, db/schema.rb, spec/models/question_spec.rb, spec/models/vote_spec.rb
=> 【Fixed】質問(questions)と投票(votes)間の関連を設定

app/models/user.rb, app/models/vote.rb, db/migrate/20160821074134_create_votes.rb, db/schema.rb, spec/models/user_spec.rb, spec/models/vote_spec.rb
=> ユーザー(users)と投票(votes)間の関連を設定

app/models/tag.rb, app/models/tag_relation.rb, db/migrate/20160821060841_create_tag_relations.rb, db/schema.rb, spec/models/tag_relation_spec.rb, spec/models/tag_spec.rb
=> タグ(tags)とタグ関連(tag_relations)間のrelationを設定する

spec/models/question_spec.rb, spec/models/user_spec.rb
=> tested association between users and questions

app/controllers/questions_controller.rb, app/views/layouts/application.html.erb, app/views/questions/_form.html.erb, app/views/questions/edit.html.erb, app/views/questions/index.html.erb, app/views/questions/new.html.erb, app/views/questions/show.html.erb, config/routes.rb, spec/controllers/questions_controller_spec.rb
https://github.com/norahito/dive23/issues/9
質問テーブルに関するCRUDのプロトタイプを完成する。
=> 質問テーブルに関するCRUDのプロトタイプ作成

app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
views/layouts/application.html.erbを調整しました。
header、footer、right_naviをパーシャル化。
=> 【Fixed】全体ページレイアウトを調整

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/uploaders/avatar_uploader.rb
#72 
1. gem carrierwave & rmagickインストール
2. usersテーブルにプロフィール画像用カラム、avatarが最初にすでに作成済
3. rails g uploader Avatar
4. Userモデルに、mount_uploaderの追記
5. application_controllerにavatarとavatar_cacheのパラメータを追加
→必要該当箇所のviewファイルの変更や画像表示のためのヘルパーメソッドは別issueでお願いします。
=> 【Fixed】CarrierWaveのインストールと初期設定

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss
#75 
- gem 'font-awesome-sass'インストール
- 初期設定で、assets/stylesheets/application.scssに追記
=> 【Fixed】Font Awesome導入

app/views/layouts/_header.html.erb
issues#77
・bootstrapの基本クラスを使用してNavbarを作成し機能開発に必要な画面リンクを設定する。
・CSSの設定や詳細なデザインは別イシューで。
=> 【Fixed】Navbarの作成(プロトタイプ) 

app/views/layouts/application.html.erb
#81 
#69　で部分テンプレート化したright_naviを削除します。
本家のサイトをよく見たら、right_naviの内容が、特に共通されているわけでもなかったり、
right_naviが存在しないページもありましたので。
それぞれのyieldで呼び出されるテンプレートの中に、必要な箇所は作った方が早いかなと思いましたので、
修正いたします。
=> 【Fixed】ページレイアウト（全体）修正

app/controllers/answers_controller.rb
#68 
以下実装
- 回答の閲覧は誰でも可
- 回答の投稿は、ログインユーザのみ可
- 自分の回答のみ、削除(と編集?)可
- 編集については保留
=> 【Fixed】answerコントロールの権限に関する処理実装

app/views/layouts/_header.html.erb, app/views/layouts/_menu.html.erb, app/views/layouts/application.html.erb, app/views/questions/_form.html.erb
Issues#86
・全体レイアウトにグリッドシステムの設定を適用する。
・main-menuをパーシャル化しグリッドシステムのレイアウト内に移動する。
・今回サンプルとしてviews/questions/_form.html.erbのみレイアウトを適用したが他の個別画面は別イシューで。
=> 【Fixed】全体レイアウトの調整(グリッドシステムの適用) 

app/assets/stylesheets/application.scss
application.scssに下記の２つをコメント内に追記しCSSを読み込むようにする。
= require_tree . # sytlesheetsディレクトリ以下のすべてを再帰的にインクルード(順番の保証なし)
= require_self # require_self呼び出しが行われたその場所にCSSファイルがあれば読み込む
=> 【Fixed】cssファイルのインポート設定

app/assets/stylesheets/_bootstrap-custom.scss, app/controllers/questions_controller.rb, app/views/questions/show.html.erb
#90 
cssファイルが読み込めなかったので、とりあえず、_bootstrap-custom.scssに記述していますが、
cssファイル読み込み可能に設定後、question.scssファイルを生成して、そちらに移します。
=> 【Fixed】質問詳細画面レイアウト作成

app/assets/stylesheets/_bootstrap-custom.scss, app/assets/stylesheets/question.scss
=> 【Fixed】question.scssの作成

app/assets/stylesheets/answer.scss, app/assets/stylesheets/question.scss, app/controllers/questions_controller.rb, app/models/answer.rb, app/views/answers/_form.html.erb, app/views/answers/_index.html.erb, app/views/questions/show.html.erb
#30 
以下完了
- views/questions/show.html.erbに、回答のリスト表示(例: _index.html.erb)
-  views/questions/show.html.erbに、回答入力フォーム(例: _form.html.erb)
以下、別issueで対応
回答投稿、削除時のajax用（例: index.js)
回答編集のajax用
=> 【Fixed】回答(answers)用のViewを作成

config/application.rb, db/seeds.rb
issues#93
db/seeds.rbにTagマスターのレコードを用意する。
=> 【Fixed】seedでTagマスターのレコードを生成

config/application.rb
issues#78
Timezoneの設定を初期値のUTCからJSTに変える
・画面表示時のタイムゾーンをJSTに変更
・DB保存時のタイムゾーンをシステムローカル時刻に変更
=> 【Fixed】Timezoneの設定

app/assets/stylesheets/question.scss, app/controllers/favorites_controller.rb, app/models/question.rb, app/models/user.rb, app/views/questions/_favorite_form.html.erb, app/views/questions/show.html.erb
#110 
・お気に入りボタンのviewの作成し、動き確認。うまく動かなかったので、それに伴い、favorites_controllerの修正。
・お気に入りにしているか、してないかで、お気に入りボタンの表示（主に色）が変わるように設定
・お気に入り数が1以上の場合に、お気に入りにされている数を表示
・Ajax対応するなら、別issueで。
=> 【Fixed】お気に入り登録機能、viewの設定

app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, app/uploaders/avatar_uploader.rb, app/views/layouts/_menu.html.erb, app/views/users/index.html.erb, config/routes.rb, spec/controllers/users_controller_spec.rb
#27
画像はどんな大きさの画像を登録しても、Rmagickを使って、63x63のサイズ(すでにアップされているno_image画像のサイズに合わせるました）にカットする方式を採用しました。
Rmagickをほとんど使用してことがなかったので、調べ調べやってみました。Rmagick以下も含め、改善点等あれば、ご指摘いただければ大変助かります。
=> 【Fixed】ユーザ一覧ページを作成

app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_navtab.html.erb, spec/factories/factories.rb, spec/factories/users.rb, spec/models/user_spec.rb
issues#101
・以下を登録必須項目にする。
ユーザ名
メアド
パスワード
・spec/factories/factories.rbを作成し、ダミーデータ生成部を共通化。
・ログイン・サインアップ画面の共通ヘッダ部をdevise/shared/_navtab.html.erbにパーシャル化。
・ログイン・サインアップ画面の作成に伴いユーザー編集画面側の文言を統一。
=> ユーザ登録・ログインページ作成

app/assets/stylesheets/partials/_common.scss, app/assets/stylesheets/partials/_users.scss, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/views/devise/registrations/edit.html.erb, app/views/users/_menu.html.erb, app/views/users/index.html.erb, app/views/users/show.html.erb, config/routes.rb
#28 
・ユーザ詳細（個別）ページ用のルーティング・コントローラ設定。
・ユーザ一覧ページから、ユーザ詳細ページへのリンクを設定。
・ユーザ詳細ページの構成・デザイン作成。合わせて、編集ページと共有のタブメニューを作成。
=> 【Fixed】ユーザ詳細ページ作成

app/assets/stylesheets/partials/_answer.scss, app/views/answers/_index.html.erb
#148 
忘れていたため、質問作成ユーザの表示と同様に、内容&デザイン修正しました。
=> 【Fixed】回答作成ユーザーの表示（内容＆デザイン）修正

app/controllers/votes_controller.rb
#129 
自分で作成した質問及び回答には投票できないように設定しました。
=> 【Fixed】votes_controllerの操作権限の設定

app/assets/stylesheets/partials/_question.scss, app/views/questions/_form.html.erb
#144 
質問画面（＆質問編集画面）のデザインを本家に近づけました。
=> 【Fixed】質問画面にスタイルを適用する

db/seeds.rb
issues#162
seedデータの生成に一部間違いが見つかったので修正する。
+ favorites countのセット抜け
+ 特定条件下でのvotesのanswer_idセット抜け
+ ついでにwhereをfindに変えてみた
=> 【Fixed】seedデータの修正

app/assets/stylesheets/partials/_common.scss, app/views/layouts/_footer.html.erb
=> 【Fixed】フッター作成

app/views/answers/_index.html.erb
#179 
要件外の機能のため未実装の回答編集画面へのリンクを隠す
=> 回答の編集へのリンクを隠す
